### ISSUE TITLE
Supporting dubbed anime?

### ISSUE THREAD

**Issue by vhammer-tgm** [TSedlar/anitrack#20]
This isn't really an issue as more of a request that would make me very happy. 

So I've noticed that when I watch dubbed series on 9anime (bc I'm a filthy casual and literally nothing offers the shows I want to watch in my region) it doesn't work if there's a "(Dub)" in the name. So I was wondering if there was a way to fix that - like replacing " (Dub)" with "" so that it picks up the anime as the original. At least that's my guess why it doesn't work :')

Anyway, if there would be any way this could be fixed I'd be so incredibly thankful!

Thanks for reading and for this awesome plugin! <3

**Comment by TSedlar** [comment]
Sorry for the delay in response, but this has worked for me on the few dubbed anime that I've tried out that felt normal to me to watch instead of subs (pokemon, yu-gi-oh, etc.). Care to share what anime this happened with? (specifically the link+title)

**Comment by TSedlar** [comment]
Closing since there hasn't been a response and it works for the dubs that I've tried.
