### ISSUE TITLE
MangaTrack?

### ISSUE THREAD

**Issue by thibaultmol** [TSedlar/anitrack#22]
Hi,

I was wondering if this chrome extension could be made so it also tracks manga (from sites like Crunchyroll, but also Kissmanga,...)

Cheers

**Comment by TSedlar** [comment]
I think this would be an interesting feature, and I could see myself using it. I'll mark it as an enhancement but I'm unsure when I will get to it.

**Comment by TSedlar** [comment]
I've added support for this to 2.0.0 wish should be live in a few hours. 

It supports:
- KissManga
- JaiminisBox
- MangaDex
- MangaEden
- MangaFox (FanFox)
- MangaReader
- MangaRock
- MangaStream
