### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by michaelowens** [TSedlar/anitrack#24]
**Browser:** Chromium Version 64.0.3282.99 (Developer Build) (64-bit)
**OS:** Arch Linux, Linux version 4.17.2-1-ARCH (builduser@heftig-9574) (gcc version 8.1.1 20180531 (GCC)) #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018
**AniTrack:** Current version on Chrome Web Store, connected to Kitsu

Yesterday my browser started becoming very sluggish and noticed in the task manager that AniTrack was using 100% cpu. As soon as I killed it my browser went back to normal. After this I tried re-enabling the plugin and see if I could reproduce, but I have not managed to get it to happen again so far. Figured I'd at least put it here in case anyone else has had this. I switched to a local installation of the package, so if I can get this to happen again I will see if I can find any logs on why this is happening.

Also wasn't watching anime at the time of this happening. Believe I had 1 crunchyroll tab open in the background on Queue page, maybe ~10 tabs in total.

**Comment by TSedlar** [comment]
Interesting that this is even remotely happening as all it does is execute a small check every 10 seconds, checking that at least 5 minutes has passed. So the only "heavy" (1-3 post requests) would be posted every 5 minutes. 

I'll mark this as a bug for a few days and do let me know if anything comes up.

If nothing happens within a week or so I'll close this as I'm quite unsure how that could remotely happen.

**Comment by TSedlar** [comment]
I'll close this since there hasn't been anything else happening other than the one time and it'd seem odd to happen in the first place.

Feel free to reopen if this happens again.
