### ISSUE TITLE
Firefox: Keep having to add AniList to extensions since its temporary

### ISSUE THREAD

**Issue by Ganjome** [TSedlar/anitrack#28]
I keep loading the extension and after my computer turns off it disappears and I have to add it back. Please help.

Also, if possible is there a way to make something more similar to "taiga.moe" where it's an application and it can track you beyond websites as well as to show on Discord Rich Presence. (but actually track masterani too)

**Comment by TSedlar** [comment]
That issue doesn't have anything to do with this extension, as it has no ability to remove itself from your browser/account. Try googling a broader search, such as `firefox removing extensions on restart`. You could possibly be running in safe-mode as well.

Considering taiga is a desktop application and not a browser extension, you're asking me to fully rewrite the program to work entirely differently and not even be a browser extension. So no, I won't do that.
