### ISSUE TITLE
It's not doing anything?

### ISSUE THREAD

**Issue by vhammer-tgm** [TSedlar/anitrack#29]
Sorry for annoying with such a vague problem, but I'm at the end of ideas here. 

I used Opera and Firefox and tested it on crunchyroll and funimation (Steins;Gate 0 and Angels of Death on both sites, and I waited 5 minutes or watched the whole episode). I logged in with Kitsu, it says I'm logged in too. 

But it never updates anything for me. I don't know if there should be a visual clue or any type of interface, there's just nothing when I watch anything.

Sorry I can't really pin my problem down. I use a VPN to access Funimation but even if I turn it off and try it on 9anime, it doesn't work either.

I would be grateful if you have any ideas what I could try!

**Comment by TSedlar** [comment]
Are you logged in with your email or username?

If it's your email, the Kitsu API doesn't allow profile lookups via email for userid.

You can change this by going to your profile settings and setting your profile url -- after you need to sign in with your username in the login dialog.

![](https://camo.githubusercontent.com/a52762f68f732adbcf0dc583333fbba023ac4a8a/68747470733a2f2f692e696d6775722e636f6d2f4e77774b684f712e706e67)

**Comment by TSedlar** [comment]
If there's no response as to if this worked in a day or two (as it did for the other person that had this issue), I'll be closing this as resolved.

**Comment by vhammer-tgm** [comment]
Sorry I was away for the last 3 days so I missed this. 

I am logged in with my username, yes. 
I actually discovered this thing kitsu has through another scrobbler but it sadly didn't change anything. Tested it on funimation with Izetta, waiting for the 5-minute mark to pass and nothing changed. Does the counter maybe reset if I don't have the tab on focus or something like that?

**Comment by TSedlar** [comment]
Is there a URL of the video page you can paste here? I can debug if the information isn't getting parsed correctly. Otherwise I don't know what to tell you.

**Comment by vhammer-tgm** [comment]
https://www.funimation.com/shows/angels-of-death/your-grave-is-not-here/simulcast/?lang=english

Yeah I know. It's really weird. Thanks for taking the time, I know how vague this issue is ;v;

**Comment by TSedlar** [comment]
Not sure what to tell you, it works perfectly fine for me.

![](https://i.imgur.com/zKsMg88.png)

It added it to my currently watching list just fine.

![](https://i.imgur.com/tVsOUS4.png)

You could try to open the browser console (not web console) via Ctrl+Shift+J (if firefox, dunno about chrome) and watch for any errors. It should print out the lifecycle every 10 seconds until it reaches 300,000 (milliseconds). Afterwards it will print out the data as I showed above.

**Comment by vhammer-tgm** [comment]
I couldn't find a console that printed anything like that in Opera, but it did print in Firefox!
I got an error but I'm not sure what it means. Sounds like it stops the extension from doing stuff? Maybe Opera has something similiar that stops the extension all together since I got none of the same outputs in the Opera console. Just to be sure I also disabled all adblock/block software I use but it didn't change anything. The episode is still on 1.

![image](https://user-images.githubusercontent.com/31884902/43773825-47c15594-9a47-11e8-8a76-c7e7bb797f13.png)
![image](https://user-images.githubusercontent.com/31884902/43773894-882d76a8-9a47-11e8-989d-27e1d024d82c.png)

**Comment by TSedlar** [comment]
For some reason it's not finding your user in the Kitsu API.

You can compare between [mine](https://kitsu.io/api/edge/users?filter[name]=sedarity) and [yours](https://kitsu.io/api/edge/users?filter[name]=vikahime).

I'm not too sure why that's happening (which isn't on me, that's a fault with the Kitsu API?), and how you're even able to log in if it can't find your profile at all.

This is the problem in its entirety, though. It doesn't have anything with what you're watching or anything of the sort, it's just that your profile doesn't seem to exist according to the Kitsu API.

**Comment by TSedlar** [comment]
When I filter using ["vika-hime"](https://kitsu.io/api/edge/users?filter[name]=vika-hime) instead, however, your data shows. Does it let you log in with your username being vika-hime instead of vikahime?

**Comment by vhammer-tgm** [comment]
Oh yeah, because kitsu didn't want me to use "-" in my url name. 
It's weird when I write "vika-hime" and click login, it tells me it fails (and deletes the password) but when it closes and I click again, "vika-hime" is the username and it says I'm logged in?? But it didn't work either way so I guess it failed the login. 
![image](https://user-images.githubusercontent.com/31884902/43811153-6aac5f6c-9abb-11e8-912e-88841239b1a1.png)
![image](https://user-images.githubusercontent.com/31884902/43811160-789dfc34-9abb-11e8-9462-73b16339b6da.png)

Well I tried to have the display name be the same as my url. It works in firefox now!! Yay! First I died a little because Opera was the only browser it didn't work in but after a restart it works in Opera as well!!
Really strange though because when I did the same for taiga.moe it worked with the url name despite the difference to the display name. Welp doesn't matter in the end.

Thank you so, so much for taking the time to help me with this problem!

**Comment by TSedlar** [comment]
Not a problem! I'll try to get in contact with the people at Kitsu to allow filtering by either profile or username or even email, instead of only allowing the profile name. Then others won't end up with the same problem.

Glad everything's working now!
