### ISSUE TITLE
not updating

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [TSedlar/anitrack#33]
![image](https://user-images.githubusercontent.com/35454710/49340601-666b2980-f66c-11e8-899d-1be9531071ab.png)
its saying the list is updated but its not
![image](https://user-images.githubusercontent.com/35454710/49340613-8ac70600-f66c-11e8-8bbc-37dd84923a7e.png)
i think the reason is kitsu is counting ep 285 as ep 8 on their site 
or something else?

**Comment by TSedlar** [comment]
There's nothing I can do if a website represents the episode as the total number of episodes vs relative to the amount of seasons (i.e episode 40 vs season 2 episode 16). In this specific case you'll have to manually update.

I could put in a function where clicking the menubar button can directly go to the show in Kitsu/MAL respectively, however.
