### ISSUE TITLE
Viz for manga

### ISSUE THREAD

**Issue by theKAKAN** [TSedlar/anitrack#34]
https://www.viz.com  
It has Shonen Jump manga as well as other mangas and I personally quite like the website. It's free for the latest chapters as well( _without creating an account_ ).  
I'll read the source code when I get some free time and try to implement it myself, in case no one works on it :smile:   
Example of Manga: https://www.viz.com/shonenjump/chapters/black-clover

**Comment by TSedlar** [comment]
I'll debug and publish soon, I've looked at the page and got the data I need.

```json
"viz": {
  "type": "manga",
  "urls": [
    "*://*.viz.com/*/*/*/*"
  ],
  "base_url": "(.*\/.*\/[0-9]+).*?",
  "title": "h3[class*=section_title]:visible a",
  "episode": "h3[class*=section_title]:visible span",
  "page": {
    "pattern": "div[class='page_slider_label center']",
    "processor": "([0-9]+)",
    "groups": [1]
  },
  "page_count": {
    "pattern": "div[class='page_slider_label left']",
    "processor": "([0-9]+)",
    "groups": [1]
  }
}
```

**Comment by TSedlar** [comment]
This has been added in 6e6d46a, and is already live on firefox. It will be live on the chrome store in likely less than an hour.

Enjoy, let me know if any bugs are apparent.

In case you don't know, it won't update on your Kitsu (MAL API is still down almost a year later.. but you can import your list into Kitsu from MAL, and also export from Kitsu to MAL), until you're half-way through the chapter or 3 minutes has passed.
