### ISSUE TITLE
Kitsu 403 forbidden error

### ISSUE THREAD

**Issue by bla5ter9000** [TSedlar/anitrack#36]
I tried going to Kitsu.io to look at some anime on my library but I keep getting the 403 forbidden nginx error. I accessed the site earlier today so I don't know what has changed for that to occur. 
Does anyone know how to fix this?

**Comment by TSedlar** [comment]
This isn't an issue with anitrack, but Kitsu itself if it is not loading for you. It could also be your internet connection or your ISP.
